-- MySQL Script generated by MySQL Workbench
-- Mon May 18 20:00:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escola_idiomas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola_idiomas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola_idiomas` ;
USE `escola_idiomas` ;

-- -----------------------------------------------------
-- Table `escola_idiomas`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`aluno` (
  `alun_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `alun_nome` TEXT NOT NULL,
  `alun_cpf` VARCHAR(14) NOT NULL,
  `alun_data_nascimento` DATE NOT NULL,
  `alun_telefone` VARCHAR(20) NOT NULL,
  `alun_endereco` JSON NOT NULL,
  `alun_email` TEXT NOT NULL,
  `alun_login` VARCHAR(50) NOT NULL,
  `alun_senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`alun_id`),
  UNIQUE INDEX (`alun_cpf` ASC) VISIBLE,
  UNIQUE INDEX (`alun_login` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`professor` (
  `prof_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `prof_nome` TEXT NOT NULL,
  `prof_cpf` VARCHAR(14) NOT NULL,
  `prof_telefone` VARCHAR(20) NOT NULL,
  `prof_email` TEXT NOT NULL,
  `prof_especialidade` VARCHAR(100) NOT NULL,
  `prof_login` VARCHAR(50) NOT NULL,
  `prof_senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`prof_id`),
  UNIQUE INDEX (`prof_cpf` ASC) VISIBLE,
  UNIQUE INDEX (`prof_login` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`funcionario` (
  `func_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `func_nome` TEXT NOT NULL,
  `func_cpf` VARCHAR(14) NOT NULL,
  `func_telefone` VARCHAR(20) NOT NULL,
  `func_email` TEXT NOT NULL,
  `func_endereco` JSON NOT NULL,
  `func_cargo` VARCHAR(50) NOT NULL,
  `func_data_contratacao` DATE NOT NULL,
  `func_login` VARCHAR(50) NOT NULL,
  `func_senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`func_id`),
  UNIQUE INDEX (`func_cpf` ASC) VISIBLE,
  UNIQUE INDEX (`func_login` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`curso` (
  `curs_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `curs_nome` TEXT NOT NULL,
  `curs_nivel` ENUM('Básico', 'Intermediário', 'Avançado') NOT NULL,
  `curs_carga_horaria` INT NOT NULL,
  `curs_duracao_meses` INT NOT NULL,
  `curs_descricao` TEXT NOT NULL,
  `curs_valor` DECIMAL(10,2) NOT NULL,
  `curs_status` ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
  PRIMARY KEY (`curs_id`));


-- -----------------------------------------------------
-- Table `escola_idiomas`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`turma` (
  `turm_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `curs_id` INT NOT NULL,
  `turm_nome` VARCHAR(100) NOT NULL,
  `turm_periodo` ENUM('Manhã', 'Tarde', 'Noite') NOT NULL,
  `turm_horario` JSON NOT NULL,
  `turm_limite_alunos` INT NOT NULL DEFAULT 40,
  `turm_quantidade_minima` INT NOT NULL,
  `turm_data_inicio` DATE NOT NULL,
  `turm_data_fim` DATE NOT NULL,
  `turm_status` ENUM('ativa', 'encerrada', 'lotada', 'cancelada') NOT NULL DEFAULT 'ativa',
  PRIMARY KEY (`turm_id`),
  INDEX `fk_turma_curso` (`curs_id` ASC) VISIBLE,
  CONSTRAINT `fk_turma_curso`
    FOREIGN KEY (`curs_id`)
    REFERENCES `escola_idiomas`.`curso` (`curs_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`plano` (
  `plan_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `plan_tipo` ENUM('Mensal', 'Família', 'Amigos') NOT NULL,
  `plan_descricao` TEXT NOT NULL,
  `plan_desconto` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `plan_valor` DECIMAL(10,2) NOT NULL,
  `plan_status` ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
  PRIMARY KEY (`plan_id`),
  UNIQUE INDEX (`plan_tipo` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`matricula` (
  `matr_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `alun_id` INT NOT NULL,
  `turm_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  `matr_data` DATE NOT NULL,
  `matr_status` ENUM('ativa', 'trancada', 'cancelada', 'concluida', 'pendente') NOT NULL DEFAULT 'pendente',
  `matr_desconto` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `matr_valor_final` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`matr_id`),
  UNIQUE INDEX `uq_matricula_aluno_turma` (`alun_id` ASC, `turm_id` ASC) VISIBLE,
  INDEX `fk_matricula_aluno` (`alun_id` ASC) VISIBLE,
  INDEX `fk_matricula_turma` (`turm_id` ASC) VISIBLE,
  INDEX `fk_matricula_plano` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_aluno`
    FOREIGN KEY (`alun_id`)
    REFERENCES `escola_idiomas`.`aluno` (`alun_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matricula_turma`
    FOREIGN KEY (`turm_id`)
    REFERENCES `escola_idiomas`.`turma` (`turm_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matricula_plano`
    FOREIGN KEY (`plan_id`)
    REFERENCES `escola_idiomas`.`plano` (`plan_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`pagamento` (
  `paga_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `matr_id` INT NOT NULL,
  `paga_valor` DECIMAL(10,2) NOT NULL,
  `paga_data_vencimento` DATE NOT NULL,
  `paga_data_pagamento` DATE NULL DEFAULT NULL,
  `paga_forma_pagamento` ENUM('PIX', 'Cartão', 'Boleto', 'Dinheiro') NOT NULL,
  `paga_status` ENUM('pendente', 'aprovado', 'recusado', 'cancelado', 'reembolsado', 'expirado') NOT NULL DEFAULT 'pendente',
  `paga_gateway` VARCHAR(50) NOT NULL,
  `paga_gateway_id` VARCHAR(100) NULL DEFAULT NULL,
  `paga_comprovante_url` VARCHAR(255) NULL DEFAULT NULL,
  `paga_observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`paga_id`),
  UNIQUE INDEX (`paga_gateway_id` ASC) VISIBLE,
  INDEX `fk_pagamento_matricula` (`matr_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_matricula`
    FOREIGN KEY (`matr_id`)
    REFERENCES `escola_idiomas`.`matricula` (`matr_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`atendimento` (
  `aten_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `alun_id` INT NOT NULL,
  `func_id` INT NOT NULL,
  `aten_data_hora` DATETIME NOT NULL,
  `aten_tipo` ENUM('matrícula', 'pagamento', 'informação', 'cancelamento', 'suporte') NOT NULL,
  `aten_descricao` TEXT NOT NULL,
  `aten_status` ENUM('finalizado', 'pendente', 'cancelado') NOT NULL DEFAULT 'finalizado',
  PRIMARY KEY (`aten_id`),
  INDEX `fk_atendimento_aluno` (`alun_id` ASC) VISIBLE,
  INDEX `fk_atendimento_funcionario` (`func_id` ASC) VISIBLE,
  CONSTRAINT `fk_atendimento_aluno`
    FOREIGN KEY (`alun_id`)
    REFERENCES `escola_idiomas`.`aluno` (`alun_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atendimento_funcionario`
    FOREIGN KEY (`func_id`)
    REFERENCES `escola_idiomas`.`funcionario` (`func_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`aula` (
  `aula_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `turm_id` INT NOT NULL,
  `prof_id` INT NOT NULL,
  `aula_data` DATE NOT NULL,
  `aula_conteudo` TEXT NOT NULL,
  `aula_observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`aula_id`),
  INDEX `fk_aula_turma` (`turm_id` ASC) VISIBLE,
  INDEX `fk_turma_professor` (`prof_id` ASC) VISIBLE,
  CONSTRAINT `fk_aula_turma`
    FOREIGN KEY (`turm_id`)
    REFERENCES `escola_idiomas`.`turma` (`turm_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_professor`
    FOREIGN KEY (`prof_id`)
    REFERENCES `escola_idiomas`.`professor` (`prof_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`frequencia` (
  `freq_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `aula_id` INT NOT NULL,
  `matr_id` INT NOT NULL,
  `freq_status` ENUM('presente', 'ausente', 'justificado') NOT NULL,
  `freq_observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`freq_id`),
  UNIQUE INDEX `uq_frequencia_aula_matricula` (`aula_id` ASC, `matr_id` ASC) VISIBLE,
  INDEX `fk_frequencia_aula` (`aula_id` ASC) VISIBLE,
  INDEX `fk_frequencia_matricula` (`matr_id` ASC) VISIBLE,
  CONSTRAINT `fk_frequencia_aula`
    FOREIGN KEY (`aula_id`)
    REFERENCES `escola_idiomas`.`aula` (`aula_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_frequencia_matricula`
    FOREIGN KEY (`matr_id`)
    REFERENCES `escola_idiomas`.`matricula` (`matr_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `escola_idiomas`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`nota` (
  `nota_id` INT UNSIGNED NOT NULL,
  `matr_id` INT NOT NULL,
  `nota_tipo` ENUM('prova', 'atividade') NOT NULL,
  `nota_valor` DECIMAL(4,2) NOT NULL,
  `nota_data` DATETIME NOT NULL,
  `nota_observacao` TEXT NULL,
  PRIMARY KEY (`nota_id`),
  INDEX `fk_nota_matricula1_idx` (`matr_id` ASC) VISIBLE,
  CONSTRAINT `fk_nota_matricula1`
    FOREIGN KEY (`matr_id`)
    REFERENCES `escola_idiomas`.`matricula` (`matr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_idiomas`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_idiomas`.`relatorio` (
  `rela_id` INT UNSIGNED NOT NULL,
  `func_id` INT NOT NULL,
  `professor_prof_id` INT NOT NULL,
  `rela_tipo` ENUM('financeiro', 'frequência', 'acadêmico', 'matrículas', 'turmas', 'pagamentos', 'notas') NOT NULL,
  `rela_inicio` DATE NOT NULL,
  `rela_fim` DATE NOT NULL,
  `rela_data_de_geracao` DATETIME NOT NULL,
  `relatoriocol` JSON NOT NULL,
  PRIMARY KEY (`rela_id`),
  INDEX `fk_relatorio_funcionario1_idx` (`func_id` ASC) VISIBLE,
  INDEX `fk_relatorio_professor1_idx` (`professor_prof_id` ASC) VISIBLE,
  CONSTRAINT `fk_relatorio_funcionario1`
    FOREIGN KEY (`func_id`)
    REFERENCES `escola_idiomas`.`funcionario` (`func_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relatorio_professor1`
    FOREIGN KEY (`professor_prof_id`)
    REFERENCES `escola_idiomas`.`professor` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
